#!/bin/bash

# Sergey Senozhatsky, 2020
# GPLv2

RAMFS=~/initramfs/
# copy libs for test_bin apps (if any)
LIBS=(libpthread.so
	libc.so
	libzstd.so
	libz.so
	libm.so
	libgcc_s.so
	libgccpp.so
	libcrypt.so
	libunwind.so
	libaio.so
	librt.so
	libcap.so
	libelf.so
	libslang.so
	libdw.so
	liblzma.so
	libbz2.so
	libdl.so
	libresolv.so
	libtinfo.so
)

function wipe
{
	rm -fr ${RAMFS}
}

function pre
{
	mkdir -p ${RAMFS}
	cd ${RAMFS}
}

function post
{
	cd ..
}

function copy_test_bin
{
	cp -R ../initramfs_test_bin/* apps/
}

function copy_libs
{
	local ARCH

	if [ -d /lib/x86_64-linux-gnu ]; then
		echo "Creating initramfs for x86_64"
		ARCH=x86_64-linux-gnu
	else
		echo "Creating initramfs for aarch64"
		ARCH=aarch64-linux-gnu
	fi

	if [ "z${ARCH}" == "zx86_64-linux-gnu" ]; then
		cp /lib/ld-linux.so* lib/
		cp /lib/${ARCH}/libunwind* lib/

	else
		cp /lib/ld-linux-aarch64.so* lib/
		cp /lib/${ARCH}/libunwind* lib/
	fi

	for lib in ${LIBS[@]}; do
		echo "Copying ${lib}"
		cp /lib/${ARCH}/${lib}* lib/
	done
}

function create_init_script
{
	rm ./init
	touch ./init

	cat << EOF >> init
#!/bin/sh

echo "Creating mount points"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -n -t tmpfs none /dev
mount -t tracefs nodev /sys/kernel/tracing/
mount -t debugfs nodev /sys/kernel/debug/

echo "Creating devnodes"
mknod -m 622 /dev/console c 5 1
mknod -m 662 /dev/ttyAMA0 c 204 64
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9

echo "Setting up symlinks"
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr
ln -s /proc/kcore /dev/core
mkdir /dev/pts
mkdir /dev/shm

echo "Mounting fs-s"
mount -t devpts -o gid=4,mode=620 none /dev/pts
mount -t tmpfs none /dev/shm

echo "well, well, well..."

setsid cttyhack sh
EOF
}

function new
{
	local VER=$(uname -r)

	mkdir -p etc proc sys usr/bin usr/sbin usr/lib tmp apps dev
	ln -s usr/bin bin
	ln -s usr/sbin sbin
	ln -s usr/lib lib
	cd bin
	sudo busybox --install .
	cd ../

	mkdir -p lib/modules
	cp -R /lib/modules/${VER} lib/modules/

	copy_libs
	cp -R /etc/ld.so.c* etc/

	create_init_script
	copy_test_bin
	chmod +x init
	cp /bin/dmesg bin/
}

function compress
{
	find . -print0 | cpio --null -ov --format=newc | gzip -1 > ~/initramfs.cpio.gz
}

if [ "z$1" == "znew" ]; then
	wipe
	pre
	new
else
	pre
	copy_test_bin
fi
compress
post
