#!/bin/sh

# Sergey Senozhatsky, 2020
# GPLv2

RAMFS=~/initramfs/
# copy libs for test_bin apps (if any)
LIBS=(/lib/ld-linux-aarch64.so.1
	/lib/libm.so.6
	/lib/libaio.so.1
	/lib/libcrypt.so.1
	/lib/librt.so.1
	/lib/libz.so.1
	/lib/libdl.so.2
	/lib/libpthread.so.0
	/lib/libc.so.6
	/lib/libpthread.so.0
	/lib/libdl.so.2
	/lib/libelf.so.1
	/lib/libdw.so.1
	/lib/libunwind.so.8
	/lib/libunwind-aarch64.so.8
	/lib/libslang.so.2
	/lib/libz.so.1
	/lib/liblzma.so.5
	/lib/libzstd.so.1
	/lib/libcap.so.2
	/lib/libbz2.so.1.0
	/lib/libgcc_s.so.1
)

function wipe
{
	rm -fr ${RAMFS}
}

function pre
{
	mkdir -p ${RAMFS}
	cd ${RAMFS}
}

function post
{
	cd ..
}

function copy_test_bin
{
	cp -R ../initramfs_test_bin/* apps/
}

function copy_libs
{
	for lib in ${LIBS[@]}; do
		echo "Copying ${lib}"
		cp ${lib} lib/
	done
}

function create_init_script
{
	rm init
	touch init
	cat << EOF >> init
#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -n -t tmpfs none /dev
mount -t tracefs nodev /sys/kernel/tracing/
mount -t debugfs nodev /sys/kernel/debug/

mknod -m 622 /dev/console c 5 1
mknod -m 662 /dev/ttyAMA0 c 204 64
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr
ln -s /proc/kcore /dev/core
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts -o gid=4,mode=620 none /dev/pts
mount -t tmpfs none /dev/shm

echo "well, well, well..."

setsid cttyhack sh
EOF
}

function new
{
	mkdir -p etc proc sys usr/bin usr/sbin usr/lib tmp apps dev
	ln -s usr/bin bin
	ln -s usr/sbin sbin
	ln -s usr/lib lib
	cd bin
	sudo busybox --install .
	cd ../

	mkdir -p lib/modules
	cp -R /lib/modules/* lib/modules/

	copy_libs
	cp -R /etc/ld.so.c* etc/

	create_init_script
	copy_test_bin
	chmod +x init
	cp /bin/dmesg bin/
}

function compress
{
	find . -print0 | cpio --null -ov --format=newc | gzip -9 > ~/initramfs.cpio.gz
}

if [ "z$1" == "znew" ]; then
	wipe
	pre
	new
else
	pre
	copy_test_bin
fi
compress
post
