#!/bin/sh

# Sergey Senozhatsky, 2020
# GPLv2

# Q=qemu-system-aarch64

Q=/media/dev/qemu/aarch64-softmmu/qemu-system-aarch64
INITRAMFS=~/initramfs.cpio.gz
KERNEL=/boot/kernel8.img

${Q} -enable-kvm \
	-m 2512 \
	-cpu host \
	-smp cpus=4 \
	-M virt \
	-serial stdio \
	-kernel ${KERNEL} \
	-initrd ${INITRAMFS}
