#!/bin/sh

# Sergey Senozhatsky, 2020
# GPLv2

Q=qemu-system-aarch64
INITRAMFS=/home/ss/initramfs.cpio.gz
KERNEL=/boot/vmlinuz-latest

${Q} --enable-kvm \
	-m 2512 \
	-cpu host \
	-smp cpus=4 \
	-M virt \
	-nographic \
	-curses \
	-kernel ${KERNEL} \
	-initrd ${INITRAMFS}
